"""Add per-user permission overrides

Revision ID: 0004_user_permissions
Revises: 0003_login_id
"""

from typing import Sequence, Union

from alembic import op

revision: str = "0004_user_permissions"
down_revision: Union[str, None] = "0003_login_id"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        create table if not exists public.user_permissions (
            id bigint generated by default as identity primary key,
            user_id integer not null references public.users(id) on delete cascade,
            permission_key varchar(255) not null,
            allowed boolean not null default false,
            created_at timestamptz not null default now(),
            updated_at timestamptz not null default now(),
            unique(user_id, permission_key)
        )
        """
    )
    op.execute("create index if not exists ix_user_permissions_user_id on public.user_permissions(user_id)")
    op.execute("create index if not exists ix_user_permissions_key on public.user_permissions(permission_key)")


def downgrade() -> None:
    op.execute("drop table if exists public.user_permissions")
