import { useCallback,useEffect,useState } from 'react';
import { Plus,RefreshCw,Search,X } from 'lucide-react';
import MainLayout from '../layouts/MainLayout';
import { useAccess } from '../context/AccessContext';
import { useAuth } from '../context/AuthContext';
import api from '../api/axios';

const empty={company_name:'',gstin:'',pan:'',cin:'',registration_no:'',billing_address:'',city:'',state:'',pincode:'',branch:'',branch_region:'UTTARAKHAND',billing_cycle:'MONTHLY',contact_person:'',contact_email:'',contact_phone:'',accounts_contact_name:'',accounts_email:'',accounts_phone:'',credit_terms_days:30,service_verticals:[],contract_start_date:'',contract_end_date:'',field_officer_ids:[],portal_user_id:null,is_active:true,notes:''};
const groups=[['Company & registration',[['company_name','Company / legal name',true],['gstin','GSTIN',true],['pan','PAN'],['cin','CIN'],['registration_no','Other registration number']]],['Billing & coordination',[['billing_address','Billing address',true],['city','City'],['state','State'],['pincode','PIN code'],['branch_region','Region',true],['branch','Coordinating branch'],['billing_cycle','Billing cycle'],['credit_terms_days','Credit terms (days)',false,'number']]],['Contacts',[['contact_person','Primary contact',true],['contact_email','Contact email',true,'email'],['contact_phone','Contact mobile',true],['accounts_contact_name','Accounts contact'],['accounts_email','Accounts email',false,'email'],['accounts_phone','Accounts mobile']]],['Contract summary',[['contract_start_date','Contract start',false,'date'],['contract_end_date','Contract end',false,'date'],['notes','Notes']]]];
const cls='mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm focus:border-teal-600 focus:outline-none focus:ring-2 focus:ring-teal-600/10';
function errorText(err){const d=err.response?.data?.detail;return Array.isArray(d)?d.map(x=>x.msg.replace(/^Value error, /,'')).join(' '):typeof d==='string'?d:'Unable to complete this action. Please retry.';}

export default function Clients(){
 const {can}=useAccess();const {user}=useAuth();
 const [rows,setRows]=useState([]),[options,setOptions]=useState({branches:[],staff:[],portal_accounts:[]}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('ALL'),[selected,setSelected]=useState(null),[form,setForm]=useState(null),[dirty,setDirty]=useState(false);
 const internal=user.role!=='CLIENT';
 const load=useCallback(async()=>{setLoading(true);try{const [directory,choices]=await Promise.all([api.get('/erp/clients'),internal?api.get('/erp/clients/options'):Promise.resolve({data:{branches:[],staff:[],portal_accounts:[]}})]);setRows(directory.data);setOptions(choices.data);setError('');}catch(err){setError(errorText(err));}finally{setLoading(false);}},[internal]);
 useEffect(()=>{load();},[load]);
 const filtered=rows.filter(x=>(status==='ALL'||Boolean(x.is_active)===(status==='ACTIVE'))&&[x.client_code,x.company_name,x.gstin,x.contact_person,x.branch,x.field_officers].some(v=>String(v||'').toLowerCase().includes(search.toLowerCase())));
 const editable=selected?can('clients.edit'):can('clients.create');
 function change(key,value){setForm(p=>({...p,[key]:value}));setDirty(true);}
 async function open(row){setSaving(true);setError('');try{const {data}=await api.get(`/erp/clients/${row.id}`);setSelected(data);setForm({...empty,...data.profile});setDirty(false);}catch(err){setError(errorText(err));}finally{setSaving(false);}}
 function close(){if(saving||(dirty&&!window.confirm('Discard unsaved client changes?')))return;setSelected(null);setForm(null);setDirty(false);}
 async function save(e){e.preventDefault();setSaving(true);setError('');try{const profile={...form,credit_terms_days:Number(form.credit_terms_days),portal_user_id:form.portal_user_id?Number(form.portal_user_id):null};const {data}=selected?await api.patch(`/erp/clients/${selected.id}`,{version:selected.version,profile}):await api.post('/erp/clients',profile);setSelected(data);setForm({...empty,...data.profile});setDirty(false);await load();setMessage(`Saved ${data.client_code}.`);}catch(err){setError(errorText(err));}finally{setSaving(false);}}
 function field([key,label,required,type='text']){let choices=key==='branch_region'?['UTTARAKHAND','UTTAR_PRADESH','DELHI_NCR']:key==='billing_cycle'?['MONTHLY','FORTNIGHTLY','WEEKLY']:null;
  if(key==='branch')choices=['',...options.branches.map(x=>x.code),...(form.branch&&!options.branches.some(x=>x.code===form.branch)?[form.branch]:[])];
  return <label key={key} className="block text-sm font-medium text-slate-700">{label}{required&&' *'}{choices?<select className={cls} value={form[key]||''} onChange={e=>change(key,e.target.value)}>{choices.map(x=><option key={x} value={x}>{key==='branch'?(options.branches.find(b=>b.code===x)?.name||x||'Head office / no branch'):x==='DELHI_NCR'?'Delhi NCR / Noida':x.replaceAll('_',' ')}</option>)}</select>:['billing_address','notes'].includes(key)?<textarea className={cls} required={required} maxLength={key==='notes'?2000:1500} rows={3} value={form[key]||''} onChange={e=>change(key,e.target.value)}/>:<input className={cls} required={required} type={type} min={type==='number'?0:undefined} max={type==='number'?365:undefined} maxLength={type==='date'||type==='number'?undefined:255} value={form[key]||''} onChange={e=>change(key,e.target.value)}/>}</label>;
 }
 return <MainLayout><div className="space-y-5">
  <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-teal-700">Business relationships</p><h1 className="mt-1 text-2xl font-semibold">Client Master</h1><p className="mt-1 text-sm text-slate-500">Company details, contacts, billing terms and staff coordination by region and branch.</p></div><div className="flex gap-2"><button disabled={loading||saving} aria-label="Refresh clients" onClick={load} className="rounded-lg border bg-white p-2.5"><RefreshCw size={18}/></button>{can('clients.create')&&<button onClick={()=>{setSelected(null);setForm({...empty});setDirty(false);setError('');}} className="flex items-center gap-2 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16}/>Add client</button>}</div></header>
  {error&&<p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{message&&<p role="status" className="rounded-lg bg-teal-50 p-3 text-sm text-teal-800">{message}</p>}
  <div className="grid gap-3 sm:grid-cols-3">{[['Total clients',rows.length],['Active clients',rows.filter(x=>x.is_active).length],['Contracts due within 60 days',rows.filter(x=>['EXPIRED','EXPIRING_30','EXPIRING_60'].includes(x.renewal_status)).length]].map(([label,value])=><div key={label} className="rounded-xl border bg-white p-4"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</div>
  <section className="overflow-hidden rounded-xl border bg-white"><div className="flex flex-wrap gap-3 border-b p-4"><label className="flex flex-1 items-center gap-2"><Search size={16}/><input aria-label="Search clients" className="w-full min-w-40 text-sm outline-none" placeholder="Search client, GSTIN, branch or coordinator" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Client status" className="rounded-lg border px-3 py-2 text-sm" value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Client','GSTIN','Region / branch','Staff coordinators','Sites / contracts','Status','Profile'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{filtered.map(row=><tr key={row.id} className="border-t"><td className="px-4 py-4 font-medium">{row.company_name}<div className="text-xs text-slate-500">{row.client_code}</div></td><td className="px-4 py-4 text-xs">{row.gstin}</td><td className="px-4 py-4 text-xs">{row.branch_region.replaceAll('_',' ')}<div className="text-slate-500">{row.branch||'Head office'}</div></td><td className="px-4 py-4 text-xs">{row.field_officers||'Unassigned'}</td><td className="px-4 py-4 text-xs">{row.site_count} sites · {row.active_contract_count} active contracts{row.renewal_status!=='NORMAL'&&<p className="mt-1 text-amber-700">{row.renewal_status.replaceAll('_',' ')}</p>}</td><td className="px-4 py-4 text-xs">{row.is_active?'Active':'Inactive'}</td><td className="px-4 py-4"><button disabled={saving} onClick={()=>open(row)} className="font-medium text-teal-700">Open</button></td></tr>)}</tbody></table>{(loading||!filtered.length)&&<p className="p-8 text-center text-sm text-slate-500">{loading?'Loading clients…':rows.length?'No matching clients.':'No clients added yet.'}</p>}</div></section>
  {form&&<div className="fixed inset-0 z-[60] overflow-y-auto bg-slate-950/40 p-3 sm:p-8" role="dialog" aria-modal="true" aria-labelledby="client-title"><form onSubmit={save} className="mx-auto max-w-4xl space-y-5 rounded-2xl bg-white p-5 sm:p-7"><div className="flex items-start justify-between"><div><h2 id="client-title" className="text-xl font-semibold">{selected?.client_code||'New client'}</h2><p className="mt-1 text-sm text-slate-500">{selected?'Saved client profile':'Client code is allocated when saved.'}</p></div><button disabled={saving} type="button" aria-label="Close client profile" onClick={close}><X size={22}/></button></div>{error&&<p role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}
  <fieldset disabled={!editable||saving} className="space-y-6 disabled:opacity-80">{groups.map(([title,fields])=><section key={title}><h3 className="border-b pb-2 text-sm font-semibold">{title}</h3><div className="mt-3 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{fields.map(field)}</div></section>)}<section><h3 className="border-b pb-2 text-sm font-semibold">Services & staff coordination</h3><div className="mt-3 flex flex-wrap gap-5">{['SECURITY','HOUSEKEEPING','HEALTHCARE'].map(x=><label key={x} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.service_verticals.includes(x)} onChange={e=>change('service_verticals',e.target.checked?[...form.service_verticals,x]:form.service_verticals.filter(v=>v!==x))}/>{x}</label>)}</div>{editable&&<p className="mt-4 text-xs text-slate-500">Assign active internal staff. Staff responsibility must match the client’s region and branch. Add staff through Staff Master first.</p>}<div className="mt-3 grid gap-3 sm:grid-cols-2">{options.staff.map(s=><label key={s.id} className="flex items-start gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" checked={form.field_officer_ids.includes(s.id)} onChange={e=>change('field_officer_ids',e.target.checked?[...form.field_officer_ids,s.id]:form.field_officer_ids.filter(x=>x!==s.id))}/><span>{s.name}<span className="block text-xs text-slate-500">{s.staff_code} · {s.region.replaceAll('_',' ')||'General responsibility'} · {s.branch||'Head office'}</span></span></label>)}</div>{editable&&!options.staff.length&&<p className="mt-3 text-sm text-slate-500">No active operations or management staff available.</p>}{selected?.assigned_staff?.filter(s=>!options.staff.some(x=>x.id===s.id)).map(s=><label key={s.id} className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={form.field_officer_ids.includes(s.id)} onChange={()=>change('field_officer_ids',form.field_officer_ids.filter(x=>x!==s.id))}/>{s.name} · {s.status}{editable&&' · remove assignment before saving'}</label>)}</section>
  {internal&&<section><h3 className="border-b pb-2 text-sm font-semibold">Client portal & record status</h3><label className="mt-3 block text-sm">Assigned client login<select value={form.portal_user_id||''} onChange={e=>change('portal_user_id',e.target.value?Number(e.target.value):null)} className={cls}><option value="">No portal account</option>{options.portal_accounts.map(u=><option key={u.id} value={u.id}>{u.name} · {u.login_id}</option>)}</select></label><p className="mt-1 text-xs text-slate-500">Create a CLIENT account in User Management. That login can view only its assigned client record.</p><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_active} onChange={e=>change('is_active',e.target.checked)}/>Active client</label></section>}</fieldset>
  <div className="flex flex-wrap items-center justify-between gap-3 border-t pt-4"><p className="text-xs text-slate-500">GSTIN format is checked. Detailed contracts and rate cards are managed in the contracts stage.</p>{editable&&<button disabled={saving} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">{saving?'Saving…':selected?'Save changes':'Create client'}</button>}</div></form></div>}
 </div></MainLayout>;
}
