import { useCallback, useEffect, useState } from 'react';
import { Plus, RefreshCw, Search } from 'lucide-react';
import MainLayout from '../layouts/MainLayout';
import { useAccess } from '../context/AccessContext';
import api from '../api/axios';
import { MasterDialog, MasterField, HistoryList, apiError, buttonClass } from '../components/MasterForms';

const empty={client_id:'',site_name:'',address:'',city:'',state:'',postal_code:'',branch:'',contract_id:null,contact_person:'',contact_phone:'',latitude:null,longitude:null,geofence_radius_meters:100,shift_requirements:{day_shift_guards:0,night_shift_guards:0,general_shift_personnel:0,supervisor_required:false},field_officer_ids:[],is_active:true,notes:''};
export default function Sites(){
 const {can}=useAccess();
 const [rows,setRows]=useState([]),[options,setOptions]=useState({clients:[],branches:[],contracts:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('ALL'),[selected,setSelected]=useState(null),[form,setForm]=useState(null),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[history,setHistory]=useState(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [r,o]=await Promise.all([api.get('/erp/sites'),api.get('/erp/sites/options')]);setRows(r.data);setOptions(o.data);}catch(e){setError(apiError(e,'Unable to load sites.'));}finally{setLoading(false);}},[]);
 useEffect(()=>{load();},[load]);
 const editable=selected?can('sites.edit'):can('sites.create');
 const client=options.clients.find(c=>c.id===Number(form?.client_id));
 const filtered=rows.filter(r=>(status==='ALL'||r.is_active===(status==='ACTIVE'))&&[r.site_name,r.site_code,r.company_name,r.city,r.branch].join(' ').toLowerCase().includes(search.toLowerCase()));
 function change(key,value){setForm(f=>({...f,[key]:value}));setDirty(true);}
 const close=useCallback(()=>{if(saving||(dirty&&!window.confirm('Discard unsaved site changes?')))return;setForm(null);setSelected(null);setHistory(null);setDirty(false);},[saving,dirty]);
 function add(){setSelected(null);setForm({...empty,shift_requirements:{...empty.shift_requirements},field_officer_ids:[]});setHistory(null);setDirty(false);setError('');}
 async function open(row){setError('');try{const {data}=await api.get(`/erp/sites/${row.id}`);setSelected(data);setForm({...empty,...data.profile,shift_requirements:{...empty.shift_requirements,...data.profile.shift_requirements}});setHistory(null);setDirty(false);}catch(e){setError(apiError(e));}}
 async function save(e){e.preventDefault();setSaving(true);setError('');const profile={...form,client_id:Number(form.client_id),contract_id:form.contract_id?Number(form.contract_id):null,latitude:form.latitude===null||form.latitude===''?null:Number(form.latitude),longitude:form.longitude===null||form.longitude===''?null:Number(form.longitude),geofence_radius_meters:Number(form.geofence_radius_meters)};try{if(selected)await api.patch(`/erp/sites/${selected.id}`,{version:selected.version,profile});else await api.post('/erp/sites',profile);setForm(null);setSelected(null);setDirty(false);setMessage('Site saved.');await load();}catch(e){setError(apiError(e));}finally{setSaving(false);}}
 async function revisions(){try{setHistory((await api.get(`/erp/sites/${selected.id}/history`)).data);}catch(e){setError(apiError(e));}}
 function field(key,label,type='text',required=false,props={}){return <MasterField key={key} label={label} value={form[key]} type={type} onChange={v=>change(key,v)} required={required} {...props}/>;}
 return <MainLayout onAction={action=>{if(action==='add_site'&&can('sites.create'))add();}}><div className="space-y-5">
  <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-teal-700">Operations</p><h1 className="mt-1 text-2xl font-semibold">Site Master</h1><p className="mt-1 text-sm text-slate-500">Client locations, internal coordination, staffing requirements and GPS boundaries.</p></div><div className="flex gap-2"><button className={buttonClass} disabled={loading||saving} aria-label="Refresh sites" onClick={load}><RefreshCw size={18}/></button>{can('sites.create')&&<button className="flex items-center gap-2 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white" onClick={add}><Plus size={16}/>Add site</button>}</div></header>
  {error&&!form&&<p role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{message&&<p role="status" className="text-sm text-teal-700">{message}</p>}
  <div className="grid gap-3 sm:grid-cols-3">{[['Total sites',rows.length],['Active sites',rows.filter(x=>x.is_active).length],['GPS pending',rows.filter(x=>x.is_active&&(x.latitude==null||x.longitude==null)).length]].map(([name,value])=><div key={name} className="rounded-xl border bg-white p-4"><p className="text-xs text-slate-500">{name}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</div>
  <section className="overflow-hidden rounded-xl border bg-white"><div className="flex flex-wrap gap-3 border-b p-4"><label className="flex flex-1 items-center gap-2"><Search size={16}/><input aria-label="Search sites" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search site, client, city or branch" className="w-full min-w-40 text-sm outline-none"/></label><select aria-label="Site status" className={buttonClass} value={status} onChange={e=>setStatus(e.target.value)}>{['ALL','ACTIVE','INACTIVE'].map(x=><option key={x}>{x}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Site','Client / branch','Location','GPS boundary','Coordinators','Status','Profile'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t"><td className="px-4 py-4 font-medium">{r.site_name}<p className="text-xs text-slate-500">{r.site_code}</p></td><td className="px-4 py-4 text-xs">{r.company_name}<p className="text-slate-500">{r.branch||'Head office'}</p></td><td className="px-4 py-4 text-xs">{r.city}, {r.state}</td><td className="px-4 py-4 text-xs">{r.latitude==null?'Not configured':`${r.geofence_radius_meters} m`}<p className="text-slate-500">{r.latitude!=null?`${r.latitude}, ${r.longitude}`:''}</p></td><td className="px-4 py-4 text-xs">{r.assigned_staff.map(x=>x.name).join(', ')||'Unassigned'}</td><td className="px-4 py-4 text-xs">{r.is_active?'Active':'Inactive'}</td><td className="px-4 py-4"><button disabled={saving} className="font-medium text-teal-700" onClick={()=>open(r)}>Open</button></td></tr>)}</tbody></table>{(loading||!filtered.length)&&<p className="p-8 text-center text-sm text-slate-500">{loading?'Loading sites…':rows.length?'No matching sites.':'Add a client first, then create its deployment sites.'}</p>}</div></section>
  {form&&<MasterDialog title={selected?.site_code||'New deployment site'} subtitle={selected?'Saved site profile':'Site code is allocated when saved.'} error={error} saving={saving} editable={editable} onClose={close} onSubmit={save} footer={<div className="space-y-3"><p>GPS coordinates can be added later. Default boundary: 100 metres.</p>{selected&&<><button type="button" className={buttonClass} onClick={revisions}>Load revision history</button>{history&&<HistoryList rows={history}/>}</>}</div>}>
    <section><h3 className="border-b pb-2 text-sm font-semibold">Client & location</h3><div className="mt-3 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><MasterField label="Client" required disabled={Boolean(selected)} value={form.client_id} onChange={v=>{const c=options.clients.find(x=>x.id===Number(v));setForm(f=>({...f,client_id:Number(v),branch:c?.branch||'',contract_id:null,field_officer_ids:[]}));setDirty(true);}} options={[{value:'',label:'Select client'},...options.clients.map(c=>({value:c.id,label:c.company_name})),...(selected&&!client?[{value:selected.client_id,label:selected.company_name+' (inactive)'}]:[])]}/>{field('site_name','Site name','text',true)}<MasterField label="Branch" value={form.branch} disabled={Boolean(client?.branch)} onChange={v=>change('branch',v)} options={[{value:'',label:'Head office'},...options.branches.map(b=>({value:b.code,label:b.name})),...(form.branch&&!options.branches.some(b=>b.code===form.branch)?[{value:form.branch,label:form.branch+' (inactive)'}]:[])]}/>{field('city','City','text',true)}{field('state','State','text',true)}{field('postal_code','PIN code','text',true,{maxLength:6,pattern:'[1-9][0-9]{5}'})}</div><div className="mt-3">{field('address','Site address','textarea',true)}</div></section>
    <section><h3 className="border-b pb-2 text-sm font-semibold">Contact & coordination</h3><div className="mt-3 grid gap-4 sm:grid-cols-2">{field('contact_person','Contact person')}{field('contact_phone','Contact mobile','tel')}<MasterField label="Contract" value={form.contract_id||''} onChange={v=>change('contract_id',v?Number(v):null)} options={[{value:'',label:'Not linked yet'},...options.contracts.filter(c=>c.client_id===Number(form.client_id)).map(c=>({value:c.id,label:c.contract_number+' · '+c.status})),...(form.contract_id&&!options.contracts.some(c=>c.id===form.contract_id)?[{value:form.contract_id,label:'Previously linked contract'}]:[])]}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_active} onChange={e=>change('is_active',e.target.checked)}/>Active site</label></div><p className="mt-3 text-xs text-slate-500">Coordinators come from internal staff assigned to this client.</p><div className="mt-2 flex flex-wrap gap-4">{(client?.staff||[]).map(s=><label key={s.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.field_officer_ids.includes(s.id)} onChange={e=>change('field_officer_ids',e.target.checked?[...form.field_officer_ids,s.id]:form.field_officer_ids.filter(x=>x!==s.id))}/>{s.name} · {s.staff_code}</label>)}{selected?.assigned_staff.filter(s=>!(client?.staff||[]).some(x=>x.id===s.id)).map(s=><label key={s.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.field_officer_ids.includes(s.id)} onChange={()=>change('field_officer_ids',form.field_officer_ids.filter(x=>x!==s.id))}/>{s.name} · {s.status}{editable?' (remove before saving)':''}</label>)}</div></section>
    <section><h3 className="border-b pb-2 text-sm font-semibold">Staffing & GPS</h3><div className="mt-3 grid gap-4 sm:grid-cols-3">{[['day_shift_guards','Day shift personnel'],['night_shift_guards','Night shift personnel'],['general_shift_personnel','General shift personnel']].map(([key,label])=><MasterField key={key} label={label} type="number" min="0" max="1000" value={form.shift_requirements[key]} onChange={v=>change('shift_requirements',{...form.shift_requirements,[key]:Number(v)})}/>)}{field('latitude','Latitude','number',false,{min:-90,max:90,step:'any'})}{field('longitude','Longitude','number',false,{min:-180,max:180,step:'any'})}{field('geofence_radius_meters','GPS boundary (metres)','number',true,{min:10,max:1000})}</div><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={form.shift_requirements.supervisor_required} onChange={e=>change('shift_requirements',{...form.shift_requirements,supervisor_required:e.target.checked})}/>Supervisor required</label></section>
    {field('notes','Coordination notes','textarea')}

  </MasterDialog>}
 </div></MainLayout>;
}
