
from uuid import UUID
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import text
from sqlalchemy.orm import Session
from app.api.deps import require_hr_or_admin
from app.core.database import get_db

router = APIRouter()

EMPLOYEE_FIELDS = [
    "name","phone","status","intimation_id","dob","gender","designation","branch",
    "site_id","joining_date","category","aadhaar_no","pan_no","permanent_address",
    "present_address","emergency_contact","marital_status","status_reason","client_id",
]

@router.get("")
def list_employees(db: Session = Depends(get_db), current_user=Depends(require_hr_or_admin)):
    return [dict(r) for r in db.execute(text("select * from employees order by created_at desc")).mappings().all()]

@router.post("", status_code=201)
def create_employee(payload: dict, db: Session = Depends(get_db), current_user=Depends(require_hr_or_admin)):
    required=["name","phone","designation","client_id","joining_date","category"]
    missing=[k for k in required if not payload.get(k)]
    if missing:
        raise HTTPException(422, f"Missing required fields: {', '.join(missing)}")

    data={k:payload[k] for k in EMPLOYEE_FIELDS if k in payload}
    data.setdefault("status","active")

    bank_keys={"bank_account_no","bank_name","bank_branch","bank_ifsc"}
    bank={k:payload.get(k) for k in bank_keys}
    bank_present=any(bank.values())
    if bank_present and not all(bank.values()):
        raise HTTPException(422, "Bank account, bank name, branch and IFSC are required together.")
    if bank_present and not payload.get("ifsc_verified"):
        raise HTTPException(422, "IFSC must be verified before the employee can be created.")

    try:
        cols=", ".join(data); binds=", ".join(f":{k}" for k in data)
        row=db.execute(
            text(f"insert into employees ({cols}) values ({binds}) returning *"),
            data
        ).mappings().one()

        if bank_present:
            db.execute(
                text("""
                    insert into employee_bank_accounts
                      (employee_id, account_number, bank_name, branch, ifsc_code, ifsc_verified)
                    values
                      (:employee_id, :account_number, :bank_name, :branch, :ifsc_code, true)
                """),
                {
                    "employee_id": str(row["id"]),
                    "account_number": bank["bank_account_no"],
                    "bank_name": bank["bank_name"],
                    "branch": bank["bank_branch"],
                    "ifsc_code": str(bank["bank_ifsc"]).strip().upper(),
                },
            )
        db.commit()
        return dict(row)
    except HTTPException:
        db.rollback()
        raise
    except Exception as exc:
        db.rollback()
        raise HTTPException(409, str(exc).split("\n")[0])

@router.patch("/{employee_id}")
def update_employee(employee_id: UUID, payload: dict, db: Session = Depends(get_db), current_user=Depends(require_hr_or_admin)):
    # employee_code is deliberately excluded: it is immutable and generated by PostgreSQL.
    data={k:v for k,v in payload.items() if k in EMPLOYEE_FIELDS and k != "employee_code"}
    if not data:
        raise HTTPException(422,"No editable fields supplied")
    data["id"]=str(employee_id)
    sets=", ".join(f"{k}=:{k}" for k in data if k!="id")
    row=db.execute(text(f"update employees set {sets} where id=:id returning *"),data).mappings().first()
    if not row:
        db.rollback()
        raise HTTPException(404,"Employee not found")
    db.commit()
    return dict(row)
