-- Single-company master. Legal records are accessed only through ERP backend
-- authorization; browser Supabase roles receive no direct table access.
create table public.company_settings (
  id integer primary key check (id = 1),
  profile jsonb not null default '{}'::jsonb,
  version integer not null default 1 check (version > 0),
  updated_by integer references public.users(id) on delete set null,
  submitted_at timestamptz,
  submitted_by integer references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.company_settings_history (
  id integer generated by default as identity primary key,
  profile jsonb not null,
  version integer not null unique,
  changed_by integer references public.users(id) on delete set null,
  action varchar(30) not null default 'UPDATE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.company_documents (
  id integer generated by default as identity primary key,
  document_type varchar(40) not null,
  title varchar(200) not null,
  original_filename varchar(255) not null,
  storage_path varchar(500) not null unique,
  mime_type varchar(100) not null,
  size_bytes integer not null check (size_bytes > 0 and size_bytes <= 3145728),
  sha256 varchar(64) not null unique,
  document_number varchar(100) not null default '',
  issue_date varchar(10) not null default '',
  expiry_date varchar(10) not null default '',
  uploaded_by integer references public.users(id) on delete set null,
  is_archived boolean not null default false,
  archived_by integer references public.users(id) on delete set null,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.company_settings enable row level security;
alter table public.company_settings_history enable row level security;
alter table public.company_documents enable row level security;
revoke all on public.company_settings, public.company_settings_history, public.company_documents from public, anon, authenticated;
revoke all on sequence public.company_settings_history_id_seq, public.company_documents_id_seq from public, anon, authenticated;
insert into public.company_settings (id,profile) values (1,'{"legal_name":"DestinLane Allied Services Pvt Ltd","display_name":"DestinLane Allied Services"}'::jsonb);
