alter table public.sites add column profile jsonb not null default '{}'::jsonb, add column version integer not null default 1, add column contract_id bigint references public.client_contracts(id) on delete restrict;
create index sites_contract_idx on public.sites(contract_id);
create unique index sites_client_name_unique on public.sites(client_id,lower(site_name));
alter table public.client_contracts add column profile jsonb not null default '{}'::jsonb,add column version integer not null default 1;
create unique index contracts_number_upper_unique on public.client_contracts(upper(contract_number));
alter table public.site_rate_cards add column contract_id bigint references public.client_contracts(id) on delete restrict,
 add column monthly_rate numeric(12,2) not null default 0,
 add column rate_basis text not null default 'DAILY' check(rate_basis in ('DAILY','HOURLY','MONTHLY')),
 add column duty_hours numeric(5,2) not null default 8 check(duty_hours between 1 and 24),
 add column billable_days integer not null default 26 check(billable_days between 1 and 31),
 add column version integer not null default 1,
 add column notes text not null default '';
create index site_rates_contract_idx on public.site_rate_cards(contract_id);
alter table public.site_rate_cards add constraint rates_nonnegative_chk check(daily_rate>=0 and hourly_rate>=0 and monthly_rate>=0 and wage_indexation_percent between 0 and 100);
alter table public.client_contracts add constraint contract_terms_chk check(credit_terms_days between 0 and 365 and wage_indexation_percent between 0 and 100);
create table public.site_code_counter (
 id integer primary key check(id=1),next_number integer not null check(next_number>=1),
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
insert into public.site_code_counter(id,next_number)
select 1,greatest(1,coalesce(max(substring(site_code from 10)::integer)+1,1)) from public.sites where site_code ~ '^SITE-DAS-[0-9]{4,}$';
create table public.commercial_master_history (
 id integer generated by default as identity primary key,
 site_id integer references public.sites(id) on delete restrict,
 contract_id bigint references public.client_contracts(id) on delete restrict,
 rate_id bigint references public.site_rate_cards(id) on delete restrict,
 changed_by integer references public.users(id) on delete set null,
 action varchar(30) not null,snapshot jsonb not null,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 check(site_id is not null or contract_id is not null or rate_id is not null)
);
create index commercial_history_site_idx on public.commercial_master_history(site_id);
create index commercial_history_contract_idx on public.commercial_master_history(contract_id);
create index commercial_history_rate_idx on public.commercial_master_history(rate_id);
create index commercial_history_actor_idx on public.commercial_master_history(changed_by);
alter table public.site_code_counter enable row level security;
alter table public.commercial_master_history enable row level security;
create policy site_counter_backend_only on public.site_code_counter for all to anon,authenticated using(false) with check(false);
create policy commercial_history_backend_only on public.commercial_master_history for all to anon,authenticated using(false) with check(false);
revoke all on public.site_code_counter,public.commercial_master_history,public.client_contracts,public.site_rate_cards from public,anon,authenticated;
revoke all on sequence public.commercial_master_history_id_seq from public,anon,authenticated;
create function public.protect_site_master_identity() returns trigger language plpgsql set search_path=pg_catalog,public as $$
begin
 if new.site_code is distinct from old.site_code or new.client_id is distinct from old.client_id then raise exception 'Saved site identity cannot be changed'; end if;
 return new;
end;
$$;
revoke all on function public.protect_site_master_identity() from public,anon,authenticated;
create trigger site_master_identity_immutable before update of site_code,client_id on public.sites for each row execute function public.protect_site_master_identity();
create function public.protect_contract_client() returns trigger language plpgsql set search_path=pg_catalog,public as $$
begin
 if new.client_id is distinct from old.client_id then raise exception 'Saved contract client cannot be changed'; end if;
 return new;
end;
$$;
revoke all on function public.protect_contract_client() from public,anon,authenticated;
create trigger contract_client_immutable before update of client_id on public.client_contracts for each row execute function public.protect_contract_client();
