alter table public.clients add column if not exists profile jsonb not null default '{}'::jsonb;
alter table public.clients add column if not exists version integer not null default 1;
create unique index if not exists clients_gstin_upper_unique on public.clients(upper(gstin)) where gstin is not null and btrim(gstin)<>'';
create unique index if not exists clients_name_lower_unique on public.clients(lower(company_name));
create unique index if not exists clients_portal_user_unique on public.clients(user_id) where user_id is not null;
create table public.client_code_counter (
 id integer primary key check(id=1),next_number integer not null check(next_number>=1),
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
insert into public.client_code_counter(id,next_number)
select 1,greatest(1,coalesce(max(substring(client_code from 7)::integer)+1,1)) from public.clients where client_code ~ '^C-DAS-[0-9]{4,}$';
create table public.client_staff_assignments (
 id integer generated by default as identity primary key,
 client_id integer not null references public.clients(id) on delete restrict,
 staff_id integer not null references public.internal_staff(id) on delete restrict,
 is_active boolean not null default true,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(client_id,staff_id)
);
create index client_staff_client_idx on public.client_staff_assignments(client_id);
create index client_staff_staff_idx on public.client_staff_assignments(staff_id);
create table public.client_master_history (
 id integer generated by default as identity primary key,
 client_id integer not null references public.clients(id) on delete restrict,
 changed_by integer references public.users(id) on delete set null,
 snapshot jsonb not null,action varchar(30) not null,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create index client_master_history_client_idx on public.client_master_history(client_id);
create index client_master_history_actor_idx on public.client_master_history(changed_by);
alter table public.client_code_counter enable row level security;
alter table public.client_staff_assignments enable row level security;
alter table public.client_master_history enable row level security;
revoke all on public.client_code_counter,public.client_staff_assignments,public.client_master_history from public,anon,authenticated;
revoke all on sequence public.client_staff_assignments_id_seq,public.client_master_history_id_seq from public,anon,authenticated;
create policy client_counter_backend_only on public.client_code_counter for all to anon,authenticated using(false) with check(false);
create policy client_staff_backend_only on public.client_staff_assignments for all to anon,authenticated using(false) with check(false);
create policy client_history_backend_only on public.client_master_history for all to anon,authenticated using(false) with check(false);
create function public.protect_client_master_code() returns trigger
language plpgsql set search_path=pg_catalog,public as $$
begin
 if new.client_code is distinct from old.client_code then raise exception 'Client codes cannot be changed'; end if;
 return new;
end;
$$;
revoke all on function public.protect_client_master_code() from public,anon,authenticated;
create trigger client_master_code_immutable before update of client_code on public.clients
for each row execute function public.protect_client_master_code();
