-- Internal company staff are separate from employees deployed to clients.
create table public.internal_staff (
 id integer generated by default as identity primary key,
 staff_code varchar(30) not null unique check(staff_code ~ '^S-DAS-[0-9]{4,}$'),
 name varchar(150) not null,
 phone varchar(10) not null unique check(phone ~ '^[6-9][0-9]{9}$'),
 profile jsonb not null,
 status varchar(20) not null default 'DRAFT' check(status in ('DRAFT','PENDING','ACTIVE','INACTIVE','TERMINATED')),
 approver_id integer references public.users(id) on delete set null,
 status_reason varchar(1000) not null default '',
 version integer not null default 1 check(version>0),
 created_by integer references public.users(id) on delete set null,
 updated_by integer references public.users(id) on delete set null,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index internal_staff_status_idx on public.internal_staff(status);
create index internal_staff_approver_idx on public.internal_staff(approver_id) where approver_id is not null;
create table public.internal_staff_code_counter (
 id integer primary key check(id=1), next_number integer not null check(next_number>=10),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
insert into public.internal_staff_code_counter(id,next_number)
select 1,greatest(10,coalesce(max(substring(employee_code from 7)::integer)+1,10))
from public.employees where employee_code ~ '^S-DAS-[0-9]{4,}$';
create table public.internal_staff_history (
 id integer generated by default as identity primary key,
 staff_id integer not null references public.internal_staff(id) on delete restrict,
 snapshot jsonb not null,
 changed_by integer references public.users(id) on delete set null,
 action varchar(30) not null,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index internal_staff_history_staff_idx on public.internal_staff_history(staff_id);
create table public.internal_staff_approval_settings (
 id integer primary key check(id=1), approver_id integer references public.users(id) on delete set null,
 version integer not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
insert into public.internal_staff_approval_settings(id) values(1);
alter table public.internal_staff enable row level security;
alter table public.internal_staff_code_counter enable row level security;
alter table public.internal_staff_history enable row level security;
alter table public.internal_staff_approval_settings enable row level security;
revoke all on public.internal_staff,public.internal_staff_code_counter,public.internal_staff_history,public.internal_staff_approval_settings from public,anon,authenticated;
revoke all on sequence public.internal_staff_id_seq,public.internal_staff_history_id_seq from public,anon,authenticated;
create policy internal_staff_backend_only on public.internal_staff for all to anon,authenticated using(false) with check(false);
create policy internal_staff_counter_backend_only on public.internal_staff_code_counter for all to anon,authenticated using(false) with check(false);
create policy internal_staff_history_backend_only on public.internal_staff_history for all to anon,authenticated using(false) with check(false);
create policy internal_staff_approval_backend_only on public.internal_staff_approval_settings for all to anon,authenticated using(false) with check(false);
-- Codes are permanent even for privileged direct database edits.
create function public.protect_internal_staff_code() returns trigger
language plpgsql set search_path = pg_catalog,public as $$
begin
 if new.staff_code is distinct from old.staff_code then
  raise exception 'Staff codes cannot be changed';
 end if;
 return new;
end;
$$;
revoke all on function public.protect_internal_staff_code() from public,anon,authenticated;
create trigger internal_staff_code_immutable before update of staff_code on public.internal_staff
for each row execute function public.protect_internal_staff_code();
