-- Missing baseline for the enterprise migrations. Apply after Alembic 0004.
-- No business records or credentials are seeded here.
alter table public.users add column if not exists password_initialized_at timestamptz;
alter table public.clients add column if not exists client_code text unique;
alter table public.sites add column if not exists branch text;

create table public.employees (
 id uuid primary key default gen_random_uuid(), employee_code text not null unique,
 name text not null, phone text not null unique, dob date, gender text,
 designation text, branch text, site_id integer references public.sites(id),
 joining_date date, category text, aadhaar_no text, pan_no text,
 permanent_address text, present_address text, emergency_contact text,
 marital_status text, intimation_id text unique, status text not null default 'DRAFT',
 status_reason text, created_at timestamptz not null default now()
);
create sequence public.employee_initial_code_seq;
create function public.generate_employee_code() returns trigger language plpgsql
set search_path=public,pg_temp as $$
begin
 if new.employee_code is null then
  new.employee_code := 'E-DAS-' || lpad(nextval('public.employee_initial_code_seq')::text,4,'0');
 end if;
 return new;
end; $$;
create trigger employee_code_default before insert on public.employees
for each row execute function public.generate_employee_code();

create table public.employee_intimations (
 id uuid primary key default gen_random_uuid(), intimation_id text not null unique,
 name text not null, phone text not null, client_id integer references public.clients(id),
 created_by integer references public.users(id), status text not null default 'INTIMATED',
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create sequence public.employee_intimation_code_seq;
create function public.generate_employee_intimation_id() returns trigger language plpgsql
set search_path=public,pg_temp as $$
declare code text;
begin
 if new.intimation_id is null then
  code := nextval('public.employee_intimation_code_seq')::text;
  new.intimation_id := 'INT-DAS-' || lpad(code,greatest(4,length(code)),'0');
 end if;
 return new;
end; $$;
create trigger employee_intimation_code_default before insert on public.employee_intimations
for each row execute function public.generate_employee_intimation_id();

create table public.employee_joining_drafts (
 id uuid primary key default gen_random_uuid(),
 intimation_id uuid not null references public.employee_intimations(id),
 employee_id uuid not null unique references public.employees(id),
 status text not null default 'DRAFT', created_by integer references public.users(id),
 last_saved_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.employee_bank_accounts (
 id uuid primary key default gen_random_uuid(),
 employee_id uuid not null unique references public.employees(id), account_number text not null,
 bank_name text not null, branch text, ifsc_code text not null, ifsc_verified boolean not null default false,
 updated_at timestamptz not null default now()
);
create table public.employee_approval_categories (
 id integer generated by default as identity primary key, category_name text not null,
 task_type text not null default 'EMPLOYEE_JOINING', is_active boolean not null default true,
 approver_user_id integer references public.users(id), is_final_approver boolean not null default false,
 sequence_order integer not null default 1, updated_at timestamptz not null default now()
);
create table public.employee_approval_requests (
 id uuid primary key default gen_random_uuid(), employee_id uuid not null references public.employees(id),
 category_id integer references public.employee_approval_categories(id), assigned_to integer references public.users(id),
 submitted_by integer references public.users(id), status text not null default 'PENDING', remarks text,
 decided_by integer references public.users(id), submitted_at timestamptz not null default now(), decided_at timestamptz
);
create table public.employee_documents (
 id uuid primary key default gen_random_uuid(), employee_id uuid not null references public.employees(id),
 document_type text not null, document_url text, document_number text, issuing_authority text,
 issue_date date, expiry_date date, status text not null default 'VALID', metadata jsonb not null default '{}',
 original_filename text not null, storage_path text not null unique, mime_type text not null,
 size_bytes integer not null check(size_bytes between 1 and 3145728), sha256 text not null,
 verification_status text not null default 'PENDING_REVIEW', verification_notes text,
 uploaded_by integer references public.users(id), verified_by integer references public.users(id), verified_at timestamptz,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(employee_id,sha256)
);
alter table public.guard_profiles add column employee_id uuid unique references public.employees(id);

-- Enterprise services use text shift values and the singular attendance table.
alter table public.shift_rosters alter column shift_type type text using shift_type::text;
alter table public.shift_rosters add constraint shift_rosters_shift_type_check check(shift_type in ('DAY','NIGHT'));
alter table public.shift_rosters rename constraint uq_site_guard_date_shift to shift_rosters_site_id_guard_id_date_shift_type_key;
create table public.attendance (
 id uuid primary key default gen_random_uuid(), employee_id uuid not null references public.employees(id),
 roster_id integer references public.shift_rosters(id), attendance_date date not null,
 status text not null default 'present', check_in_time timestamptz, check_out_time timestamptz,
 check_in_selfie_url text, check_out_selfie_url text, check_in_latitude double precision,
 check_in_longitude double precision, check_out_latitude double precision, check_out_longitude double precision,
 check_in_accuracy double precision, check_out_accuracy double precision,
 shift_hours numeric not null default 0, overtime_hours numeric not null default 0,
 late_minutes integer not null default 0, night_shift boolean not null default false,
 submitted_at timestamptz, verified_at timestamptz,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(employee_id,attendance_date)
);

-- Legacy financial/control records retained for compatibility with existing APIs.
create table public.salary_records (
 id uuid primary key default gen_random_uuid(), employee_id uuid not null references public.employees(id),
 month text not null, amount numeric not null default 0, status text not null default 'PENDING', credited_date date,
 work_days numeric not null default 0, present_days numeric not null default 0, late_days numeric not null default 0,
 leave_days numeric not null default 0, absent_days numeric not null default 0,
 basic numeric not null default 0,hra numeric not null default 0,allowances numeric not null default 0,
 gross_pay numeric not null default 0,pf numeric not null default 0,esic numeric not null default 0,
 lwf numeric not null default 0,dress_emi numeric not null default 0,net_pay numeric not null default 0,
 lifecycle_status text not null default 'DRAFT',
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.expenses (
 id uuid primary key default gen_random_uuid(), branch text,client_id integer references public.clients(id),
 category text not null,description text,amount numeric not null check(amount>=0),expense_date date not null default current_date,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.bookkeeping_ledger (
 id uuid primary key default gen_random_uuid(),entry_date date not null default current_date,account_type text not null,
 reference_type text,reference_id text,debit numeric not null default 0,credit numeric not null default 0,description text,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.gst_collection_ledger (
 id uuid primary key default gen_random_uuid(),invoice_id integer references public.invoices(id),
 taxable_amount numeric not null default 0,cgst numeric not null default 0,sgst numeric not null default 0,
 igst numeric not null default 0,gst_amount numeric not null default 0,
 created_at timestamptz not null default now()
);
create table public.gst_itc_ledger (
 id uuid primary key default gen_random_uuid(),expense_id uuid references public.expenses(id),gst_amount numeric not null default 0,
 reconciliation_status text not null default 'PENDING',created_at timestamptz not null default now()
);
create table public.corporate_compliances (
 id uuid primary key default gen_random_uuid(),compliance_type text not null,period text,due_date date,filed_date date,
 status text not null default 'PENDING',reference_number text,notes text,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.attendance_exceptions (
 id uuid primary key default gen_random_uuid(),employee_id uuid references public.employees(id),exception_type text not null,
 description text,resolved boolean not null default false,created_at timestamptz not null default now()
);
create table public.risk_flags (
 id uuid primary key default gen_random_uuid(),trigger_code text,category text,severity text,entity_type text,entity_id text,
 description text,resolved boolean not null default false,detected_at timestamptz not null default now(),resolved_at timestamptz
);

-- Deny browser access to every baseline table; the backend owns authorization.
do $$
declare table_name text;
begin
 foreach table_name in array array['employees','employee_intimations','employee_joining_drafts',
 'employee_bank_accounts','employee_approval_categories','employee_approval_requests','employee_documents',
 'attendance','salary_records','expenses','bookkeeping_ledger','gst_collection_ledger','gst_itc_ledger',
 'corporate_compliances','attendance_exceptions','risk_flags'] loop
  execute format('alter table public.%I enable row level security',table_name);
  execute format('revoke all on public.%I from public,anon,authenticated',table_name);
 end loop;
end; $$;
