alter table public.users add column if not exists must_change_password boolean not null default false;
alter table public.users add column if not exists session_version integer not null default 0;
create unique index if not exists users_login_id_upper_unique on public.users(upper(login_id)) where login_id is not null;
create unique index if not exists users_email_lower_unique on public.users(lower(email));
create table public.account_access_audit (
 id integer generated by default as identity primary key,
 actor_id integer references public.users(id) on delete set null,
 target_id integer references public.users(id) on delete set null,
 action varchar(40) not null, details jsonb not null,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create index account_access_audit_target_idx on public.account_access_audit(target_id);
create index account_access_audit_actor_idx on public.account_access_audit(actor_id);
alter table public.account_access_audit enable row level security;
revoke all on public.account_access_audit from public,anon,authenticated;
revoke all on sequence public.account_access_audit_id_seq from public,anon,authenticated;
create policy account_access_audit_backend_only on public.account_access_audit for all to anon,authenticated using(false) with check(false);
